#!/usr/bin/env bash

set -euo pipefail

# Set up Ruby.
brew install rbenv
rbenv install --skip-existing
gem install bundler
bundle install

# Build Go[lang].
brew install go
go build hello.go

# Install Haskell Stack.
brew install haskell-stack

# Build Haskell/Scotty.
stack exec --package scotty -- ghc -Wall -O2 --make hello_scotty.hs

# Build Haskell/Servant.
stack exec --package http-client --package servant --package servant-server -- ghc -Wall -O2 --make hello_servant.hs
